# Generated by Django 3.0 on 2021-01-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pk_main_website', '0003_auto_20210123_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
