# Generated by Django 3.0 on 2021-01-23 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pk_main_website', '0004_task_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pk_main_website.Board'),
        ),
    ]
